
# Syntax highlighting
markdown:            redcarpet
highlighter:         rouge

# Permalinks
permalink:           /:title/
relative_permalinks: false

# Setup
timezone:            Europe/London # eg. Asia/Kathmandu
locale:              en_uk # eg. en_us
name:                Effective Coding Life
title:               The life and opinions of an Effective Software Developer
tagline:             'The life and opinions of an Effective Software Developer'
description: > # this means to ignore newlines until "baseurl:"
  Swift and Objective-C code, rants, thoughts, and how to add magic into your apps, 
  from the author of "Swift By Example" and "Swift 2 By Example".
url: "http://giordanoscalzo.com" # the base hostname & protocol for your site
rss:                 "http://giordanoscalzo.com/feed.xml"
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              giordanoscalzocomblog # get it on https://disqus.com/admin/

author:
  name:              Giordano
  url:               "http://giordanoscalzo.com"
  twitter:           giordanoscalzo
  github:            gscalzo
  linkedin:          giordanoscalzo

fb_admins:           ''
fb_appid:            ''

# Server
destination:         ./_site
exclude:             [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:                9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
