# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Coding Life With Giordano Scalzo
email: giordano.scalzo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Swift and Objective-C, rants, thoughts, and how to add magic into your apps, from a seasoned code wizard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://giordanoscalzo.com" # the base hostname & protocol for your site
twitter_username: giordanoscalzo
github_username:  gscalzo

# Build settings
markdown: kramdown
