baseURL = "https://gioscalzo.com/"
locale = "en-us"
title = "Gio Scalzo"
theme = "paper"
googleAnalytics = "G-B6YT2W23QZ"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

# [[menu.main]]
#   name = "Projects"
#   url = "/projects/"
#   weight = 2

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 3

[[menu.main]]
  name = "Writing"
  url = "/blog/"
  weight = 4

[params]
  description = "AI, mobile engineering, and the craft of growing people."
  github = "gscalzo"
  linkedin = "giordanoscalzo"
  twitter = "giordanoscalzo"
  rss = true

  [params.author]
    name = "Giordano Scalzo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
