baseURL = "https://gioscalzo.com/"
locale = "en-us"
title = "Giordano Scalzo"
theme = "paper"
googleAnalytics = "G-B6YT2W23QZ"
enableRobotsTXT = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

# [[menu.main]]
#   name = "Projects"
#   url = "/projects/"
#   weight = 2

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 3

[[menu.main]]
  name = "Writing"
  url = "/blog/"
  weight = 4

[params]
  description = "Giordano Scalzo is a London-based AI and engineering leader, mobile specialist, speaker, and author of six books."
  github = "gscalzo"
  linkedin = "giordanoscalzo"
  twitter = "giordanoscalzo"
  medium = "https://medium.com/@giordanoscalzo"
  stackoverflow = "https://stackoverflow.com/users/288379/giordano-scalzo"
  images = ["/images/social/giordano-scalzo.jpg"]
  rss = true

  [params.author]
    name = "Giordano Scalzo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
